language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adventurer-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: adventurerapp
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: vbxDlskWhJpn4vtaV58eMqoPyUe+npt+OjbS3DZEwmPo9YZQjjkzDrMoUZ5VA7Tv4lmq8MM2BYTuXdYSxXjcIFwN+O3u/XHjVgg7CVytrA9RQS89LDA1QEXkLr9V6JHK5WkxXJKpVphx/8VfnZzuxaID/ZAoqkj1VRP/n32S0TcEmHgSlDivCnFTY1NFj2ITFppOnT51iLAKG5tqStDeZJzqGZ/djCWBRfXozOXva3VrznM8k4j2a1RuUDD+moxyTL2jGNQLKvvOvCYistHR0TlYUirtUUAsheckxuxLQEnIhvR+T3SYqM5kpQGZ9yRDaaaE+oxoTmMWnnJTgiq9taWOGwNCHT+9P7yTsZ/UUdbCmTA8pV9jtq71/qWHkmue4xrnpLyHoI/ddsGWEFOQ7m7ZDllP2uXjbpzvM7BMTBuF2cbp4cVQxG99tfhE4RMB3Y6+neq3Ug8hTbTFJLDymgfY0Zn2IgS7jXo0Cpyzcj4tt/QRzrjC6DSbA5YRzuXJ11XAb21I0vMHrYUAOhxV3hbTLNf6qKU4d6ARNreVZuiWa/b+qbqkrze9Ry7zLXPoZLrHIdUYwi4Koou2LDmf34rv6udHF0db3/2w49o+qbpF2wldJfLGrEgFgvt2/AMxs6gQHa2UXbER71gajlulMpM/W5iW7/AOC7UcxDFd3eQ=
